CREATE DATABASE IF NOT EXISTS customer_behavior;
USE customer_behavior;

-- Initial Sanity Check
SELECT * FROM customer LIMIT 5;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM customer
  )
ORDER BY purchase_amount DESC;

-- Q3. What are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

-- Q4. How does average purchase amount differ between Standard and Express shipping?
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more than non-subscribed customers?
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        100.0 * 
        SUM(CASE 
                WHEN discount_applied = 'Yes' THEN 1 
                ELSE 0 
            END) / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. How many customers belong to the New, Returning, and Loyal segments?
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases <= 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_orders,
    item_rank
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9. Are customers with more than 5 previous purchases more likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS repeat_buyers,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (),
        2
    ) AS percentage_of_repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. Which age groups contribute the most revenue?
SELECT 
    age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q11. Within each category, which 3 products generate the highest revenue?
WITH product_revenue AS (
    SELECT 
        category,
        item_purchased,
        SUM(purchase_amount) AS total_revenue
    FROM customer
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT 
        category,
        item_purchased,
        total_revenue,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_revenue DESC
        ) AS revenue_rank
    FROM product_revenue
)
SELECT 
    category,
    item_purchased,
    ROUND(total_revenue, 2) AS total_revenue,
    revenue_rank
FROM ranked_products
WHERE revenue_rank <= 3
ORDER BY category, revenue_rank;

-- Q12. What percentage of the total revenue comes from each product category?
WITH category_revenue AS (
    SELECT 
        category,
        SUM(purchase_amount) AS category_revenue
    FROM customer
    GROUP BY category
)
SELECT 
    category,
    ROUND(category_revenue, 2) AS category_revenue,
    ROUND(
        100.0 * category_revenue /
        SUM(category_revenue) OVER (),
        2
    ) AS revenue_percentage
FROM category_revenue
ORDER BY revenue_percentage DESC;

-- Q13. Who are the top 10 customers by total spending?
SELECT 
    customer_id,
    COUNT(*) AS total_purchases,
    ROUND(SUM(purchase_amount), 2) AS total_spending,
    ROUND(AVG(purchase_amount), 2) AS average_purchase
FROM customer
GROUP BY customer_id
ORDER BY total_spending DESC
LIMIT 10;

-- Q14. Which payment methods generate the highest revenue and transaction count?
SELECT 
    payment_method,
    COUNT(*) AS total_transactions,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS average_transaction_value
FROM customer
GROUP BY payment_method
ORDER BY total_revenue DESC;